version: '3.8'

services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: anvil-node
    ports:
      - "8545:8545"
    volumes:
      - ./data:/app/data
    working_dir: /app
    entrypoint: ["sh", "-c"]
    command: |
      "if [ -f /app/data/state.json ]; then
        anvil --load-state /app/data/state.json --block-time 1 --state-interval 5 --dump-state /app/data/state.json --host 0.0.0.0 --port 8545
      else
        anvil --block-time 1 --state-interval 5 --dump-state /app/data/state.json --host 0.0.0.0 --port 8545
      fi"
    restart: unless-stopped