version: '3.8'

services:
  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    container_name: schema-registry
    ports:
      - "8081:8081"
    volumes:
      - schema_registry_data:/var/lib/schema-registry
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://host.docker.internal:9092

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    volumes:
      - kafka_ui_data:/etc/kafkaui
      - ./certs:/etc/kafkaui/ssl
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: host.docker.internal:9092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://host.docker.internal:8081

      KAFKA_CLUSTERS_1_NAME: aiven-cluster
      KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: event-handler-cluster-event-handler.d.aivencloud.com:16628
      KAFKA_CLUSTERS_1_PROPERTIES_SECURITY_PROTOCOL: SSL
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_TRUSTSTORE_LOCATION: /etc/kafkaui/ssl/truststore.jks
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: changeit
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_KEYSTORE_LOCATION: /etc/kafkaui/ssl/keystore.jks
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_KEYSTORE_PASSWORD: changeit
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_KEY_PASSWORD: changeit
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''

volumes:
  schema_registry_data:
  kafka_ui_data: