services:
  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]

volumes:
  redisdata:
